#!/bin/bash
#####################################################################################################
# Script for running cross validation of the GOR model                                              #
# 1. GOR training:                                                                                  #
#####################################################################################################

# usage: gor_training.py [-h] -p  -s  [-i] [-w ] -o

# Train GOR model

# optional arguments:
#   -h, --help                show this help message and exit
#   -p , --profile            Path to directory containing all profile files needed
#                             for training.
#   -s , --secondarystructure 
#                             Path to directory containing all secondary structures
#                             in fasta-like format needed for training.
#   -i , --ids                Path to file containing IDs of current training set.
#   -w [], --winsize []       Window size of the sliding window for training the gor
#                             model. Must be **ODD** numbered integer!
#   -o , --output             Path to training output directory.


for i in {0..4}
do
    # Vars that remain the same in each iteration:
    p="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/trainingset/seqprofile_training/"
    s="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/trainingset/dssp"
    ipath="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/trainingset/cv_ids_clean/training/train_${i}"
    o="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/outputs/gor_train_out/train${i}"
    /Users/ila/01-Unibo/02_Lab2/files_lab2_project/scripts/gor_training.py -p="${p}" -s="${s}" -i="${ipath}" -w="17" -o="${o}"
done

#####################################################################################################
# 1. GOR prediction on test sets:                                                                   #
#####################################################################################################
# usage: gor_prediction.py [-h] -m  -q  [-i] -o

# Train GOR model

# optional arguments:
#   -h, --help            show this help message and exit
#   -m , --model          Path to directory containing model csv generated by
#                         training.
#   -q , --queryprofiles 
#                         Path to directory containing all query profile files
#                         to be predicted.
#   -i , --ids            Path to file containing IDs of current training set.
#   -o , --output         Path to output directory for all predicted structures.

# Making 5 dirs holding testing output:
for j in {0..4}
do
    mkdir -p /Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/outputs/gor_test_out/test${j}
done

# Running the script
for i in {0..4}
do
    # Vars that remain the same in each iteration:
    m="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/outputs/gor_train_out/train${i}" # Name of the dir holding HEC SS W matrices
    q="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/trainingset/seqprofile_training/"
    ipath="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/trainingset/cv_ids_clean/testing/test_set${i}"
    o="/Users/ila/01-Unibo/02_Lab2/files_lab2_project/all_data/outputs/gor_test_out/test${i}"
    /Users/ila/01-Unibo/02_Lab2/files_lab2_project/scripts/gor_prediction.py -m="${m}" -q="${q}" -i="${ipath}" -o="${o}"

done
